CREATE TABLE CATEGORIES (
	IDCATEGORIES NUMBER(38,0) PRIMARY KEY NOT NULL,
	NAME	VARCHAR2(30) NOT NULL,
	DELETED NUMBER(38,0) NOT NULL
);

CREATE TABLE PLATFORMS (
	IDPLATFORM NUMBER(38,0) PRIMARY KEY NOT NULL,
	NAME VARCHAR2(30) NOT NULL,
	DELETED NUMBER(38,0) NOT NULL
);

CREATE TABLE ROLES (
	IDROLES NUMBER(38,0) PRIMARY KEY NOT NULL,
	NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE PERMITS (
	IDPERMITS NUMBER(38,0) PRIMARY KEY NOT NULL,
	NAME VARCHAR2(30)	NOT NULL
);

CREATE TABLE ROL_PERM (
	IDROLPERM NUMBER(38,0) PRIMARY KEY NOT NULL,
	IDPERMITS NUMBER(38,0) NOT NULL,
	IDROLES NUMBER(38,0) NOT NULL
);

CREATE TABLE USER_ROLES (
	IDUSERROL NUMBER(38,0) PRIMARY KEY NOT NULL,
	IDUSER NUMBER (38,0) NOT NULL,
	IDROLES NUMBER(38,0) NOT NULL
);

INSERT INTO CATEGORIES VALUES(1,'ACTION',0);	
INSERT INTO CATEGORIES VALUES(2,'SHOOTER',0);
INSERT INTO CATEGORIES VALUES(3,'SPORTS',0);

INSERT INTO PLATFORMS VALUES(1,'PLAY STATION',0);
INSERT INTO PLATFORMS VALUES(2,'NINTENDO',0);
INSERT INTO PLATFORMS VALUES(3,'XBOX',0);

INSERT INTO ROLES VALUES(1,'ADMIN');
INSERT INTO ROLES VALUES(2,'USER');

INSERT INTO PERMITS VALUES(1,'USERS MANAGEMENT');
INSERT INTO PERMITS VALUES(2,'CUSTOMERS MANAGEMENT');
INSERT INTO PERMITS VALUES(1,'ORDERS MANAGEMENT');
INSERT INTO PERMITS VALUES(3,'PRODUCTS MANAGEMENT');
INSERT INTO PERMITS VALUES(4,'CATEGORIES MANAGEMENT');
INSERT INTO PERMITS VALUES(5,'PLATFORMS MANAGEMENT');

ALTER TABLE ROL_PERM ADD CONSTRAINT FK_ROL_PERM_IDROL FOREIGN KEY (IDROLES) REFERENCES ROLES(IDROLES);
ALTER TABLE ROL_PERM ADD CONSTRAINT FK_ROL_PERM_IDPERM FOREIGN KEY (IDPERMITS) REFERENCES PERMITS(IDPERMITS);

ALTER TABLE USER_ROLES ADD CONSTRAINT FK_USER_ROLES_IDUSER FOREIGN KEY (IDUSER) REFERENCES USERS(IDUSER);
ALTER TABLE USER_ROLES ADD CONSTRAINT FK_USER_ROLES_IDROLES FOREIGN KEY (IDROLES) REFERENCES ROLES(IDROLES);
