--------------------------------------------------------
-- Archivo creado  - lunes-febrero-18-2019   
--------------------------------------------------------
DROP TABLE "VIDEOGAMESERP"."INVOICES" cascade constraints;
DROP TABLE "VIDEOGAMESERP"."LINE" cascade constraints;
DROP TABLE "VIDEOGAMESERP"."ORDERS_INVOICES" cascade constraints;
DROP TABLE "VIDEOGAMESERP"."PRODUCTS_INVOICES" cascade constraints;
DROP TABLE "VIDEOGAMESERP"."PAYMENTMETHODS" cascade constraints;
--------------------------------------------------------
--  DDL for Table INVOICES
--------------------------------------------------------

  CREATE TABLE "VIDEOGAMESERP"."INVOICES" 
   (	"NUM_INVOICE" NUMBER(38,0), 
	"DATETIME" DATE, 
	"REFCUSTOMER" NUMBER(38,0), 
	"NET_AMOUNT" NUMBER(11,2) DEFAULT 0, 
	"AMOUNT" NUMBER(11,2) DEFAULT 0, 
	"DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "VIDEOGAMESERP"."INVOICES"."DELETED" IS '0 no deleted, 1 si deleted';
--------------------------------------------------------
--  DDL for Table LINE
--------------------------------------------------------

  CREATE TABLE "VIDEOGAMESERP"."LINE" 
   (	"ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(60 BYTE), 
	"AMOUNT" NUMBER(11,2) DEFAULT 0, 
	"PRICE" FLOAT(126) DEFAULT 0, 
	"REFINVOICE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS_INVOICES
--------------------------------------------------------

  CREATE TABLE "VIDEOGAMESERP"."ORDERS_INVOICES" 
   (	"IDORDERINV" NUMBER(38,0), 
	"IDORDER" NUMBER(38,0), 
	"IDINVOICE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS_INVOICES
--------------------------------------------------------

  CREATE TABLE "VIDEOGAMESERP"."PRODUCTS_INVOICES" 
   (	"IDPROINV" NUMBER(38,0), 
	"IDPRODUCT" NUMBER(38,0), 
	"IDINVOICE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENTMETHODS
--------------------------------------------------------

  CREATE TABLE "VIDEOGAMESERP"."PAYMENTMETHODS" 
   (	"IDPAYMENTMETHOD" NUMBER, 
	"PAYMENTMETHOD" VARCHAR2(100 BYTE), 
	"DELETED" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into VIDEOGAMESERP.INVOICES
SET DEFINE OFF;
REM INSERTING into VIDEOGAMESERP.LINE
SET DEFINE OFF;
REM INSERTING into VIDEOGAMESERP.ORDERS_INVOICES
SET DEFINE OFF;
REM INSERTING into VIDEOGAMESERP.PRODUCTS_INVOICES
SET DEFINE OFF;
REM INSERTING into VIDEOGAMESERP.PAYMENTMETHODS
SET DEFINE OFF;
Insert into VIDEOGAMESERP.PAYMENTMETHODS (IDPAYMENTMETHOD,PAYMENTMETHOD,DELETED) values ('1','Cash','0');
Insert into VIDEOGAMESERP.PAYMENTMETHODS (IDPAYMENTMETHOD,PAYMENTMETHOD,DELETED) values ('2','Wire Transfer','0');
Insert into VIDEOGAMESERP.PAYMENTMETHODS (IDPAYMENTMETHOD,PAYMENTMETHOD,DELETED) values ('3','Credit Card','0');
Insert into VIDEOGAMESERP.PAYMENTMETHODS (IDPAYMENTMETHOD,PAYMENTMETHOD,DELETED) values ('4','Paypal','0');
Insert into VIDEOGAMESERP.PAYMENTMETHODS (IDPAYMENTMETHOD,PAYMENTMETHOD,DELETED) values ('5','Cash on Delivery','0');
--------------------------------------------------------
--  DDL for Index INVOICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIDEOGAMESERP"."INVOICES_PK" ON "VIDEOGAMESERP"."INVOICES" ("NUM_INVOICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIDEOGAMESERP"."LINE_PK" ON "VIDEOGAMESERP"."LINE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_INVOICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIDEOGAMESERP"."ORDERS_INVOICES_PK" ON "VIDEOGAMESERP"."ORDERS_INVOICES" ("IDORDERINV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_INVOICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIDEOGAMESERP"."PRODUCTS_INVOICES_PK" ON "VIDEOGAMESERP"."PRODUCTS_INVOICES" ("IDPROINV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAYMENTMETHODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIDEOGAMESERP"."PAYMENTMETHODS_PK" ON "VIDEOGAMESERP"."PAYMENTMETHODS" ("IDPAYMENTMETHOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INVOICES
--------------------------------------------------------

  ALTER TABLE "VIDEOGAMESERP"."INVOICES" ADD CONSTRAINT "INVOICES_PK" PRIMARY KEY ("NUM_INVOICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIDEOGAMESERP"."INVOICES" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."INVOICES" MODIFY ("REFCUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."INVOICES" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."INVOICES" MODIFY ("NUM_INVOICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINE
--------------------------------------------------------

  ALTER TABLE "VIDEOGAMESERP"."LINE" ADD CONSTRAINT "LINE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIDEOGAMESERP"."LINE" MODIFY ("REFINVOICE" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."LINE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."LINE" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."LINE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS_INVOICES
--------------------------------------------------------

  ALTER TABLE "VIDEOGAMESERP"."ORDERS_INVOICES" ADD CONSTRAINT "ORDERS_INVOICES_PK" PRIMARY KEY ("IDORDERINV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIDEOGAMESERP"."ORDERS_INVOICES" MODIFY ("IDINVOICE" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."ORDERS_INVOICES" MODIFY ("IDORDER" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."ORDERS_INVOICES" MODIFY ("IDORDERINV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS_INVOICES
--------------------------------------------------------

  ALTER TABLE "VIDEOGAMESERP"."PRODUCTS_INVOICES" ADD CONSTRAINT "PRODUCTS_INVOICES_PK" PRIMARY KEY ("IDPROINV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VIDEOGAMESERP"."PRODUCTS_INVOICES" MODIFY ("IDINVOICE" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."PRODUCTS_INVOICES" MODIFY ("IDPRODUCT" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."PRODUCTS_INVOICES" MODIFY ("IDPROINV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENTMETHODS
--------------------------------------------------------

  ALTER TABLE "VIDEOGAMESERP"."PAYMENTMETHODS" MODIFY ("IDPAYMENTMETHOD" NOT NULL ENABLE);
  ALTER TABLE "VIDEOGAMESERP"."PAYMENTMETHODS" ADD CONSTRAINT "PAYMENTMETHODS_PK" PRIMARY KEY ("IDPAYMENTMETHOD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
